# Autogenerated by nbdev

d = { 'settings': { 'branch': 'main',
                'doc_baseurl': '/mrcnn_line_segmentation',
                'doc_host': 'https://sethdroberts.github.io',
                'git_url': 'https://github.com/sethdroberts/mrcnn_line_segmentation',
                'lib_path': 'mrcnn_line_segmentation'},
  'syms': {'mrcnn_line_segmentation.core': {'mrcnn_line_segmentation.core.foo': ('core.html#foo', 'mrcnn_line_segmentation/core.py')}}}
